### ISSUE TITLE
☂ Add data in suburban Atlanta

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#2407]
Looks like data missing around Atlanta.

**Atlanta urban and suburban core:**

- [x] Marietta city: https://github.com/openaddresses/openaddresses/pull/2500
- [x] Cobb county (Marietta is seat?): https://github.com/openaddresses/openaddresses/issues/2497 - but expensive paid data ($20k)
  - Alternative source: Cobb County, GA Parcels #2609
- [x] Decator / DeKalb #2599
- [x] Gwinnett County, Georgia #2600
- [x] to the south: Clayton County, GA #2601 
- [x] to the south: Henry County, GA #2614 
- [x] to the south: Fayatte County, GA #2607

**Exurbs of Atlanta:**

- [x] Jackson County, GA https://github.com/openaddresses/openaddresses/issues/2604
- [x] Forsyth County, GA #2603 
- [x] Hall County, GA #2602 
- [ ] Coweta County, GA #2608 (south)
- [ ] Haralson County, GA #2613 (far exurbs)
- [ ] Floyd County, GA #2619 (north-west)
- [ ] Polk County, GA #2617 (north-west)
- [ ] Barrow County, GA #2456 (east over by Athens)

**Comment by nvkelso** [comment]
Exurbs of Atlanta:

- [ ] Jackson County, GA https://github.com/openaddresses/openaddresses/issues/2604

**Comment by arch0345** [comment]
It looks like all the issues linked to the tasks above have been resolved
