### ISSUE TITLE
Launching

### ISSUE THREAD

**Issue by lxbarth** [openaddresses/openaddresses#63]
Let's launch this sucker. Here's what I'm seeing outstanding:
- [x] Create a downloadable package https://github.com/osmlab/addresses/issues/20
- [x] One source per file - See #64 
- [x] Ideally cache assets https://github.com/osmlab/addresses/issues/17
- [x] Split + move to openaddresses organization https://github.com/osmlab/addresses/issues/62
- [x] Do a blog post

Anything I'm missing?
